name: Reset Fork

on:
  workflow_dispatch:

jobs:
  reset:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout fork
        uses: actions/checkout@v4

      - name: Reset to upstream
        run: |
          git remote add upstream https://github.com/florisboard/florisboard.git
          git fetch upstream
          git reset --hard upstream/main
          git push origin main --force
